### ISSUE TITLE
Unexpected empty event when fetching events on block 703071. 

### ISSUE THREAD

**Issue by AlexZhenWang** [cennznet/api.js#158] opened 2020-08-24 01:58 UTC
Hi guys, I got an empty event when fetching events on block 703071. 

After calling `await this.api.query.system.events.at(blockHash).toPromise()`, 
I got:
```'[{"phase":{"ApplyExtrinsic":0},"event":{"index":"0x0000","data":[{"weight":10000,"class":"Operational","paysFee":true}]},"topics":[]}, {"phase":{"ApplyExtrinsic":1},"event":{"index":"0x0000","data":[{"weight":10000,"class":"Normal","paysFee":true}]},"topics":[]}, {"phase":{"ApplyExtrinsic":2},"event":{"index":"0x0303","data":[2,{"symbol":"0xd373896af0d70b40c8b80af075f2761043c1a63798a2c5cb95d68f1d66bd2f0000000040228a097ac4865aa84c3b4b0000020000000000102700000001","decimalPlaces":0}]},"topics":[]}, {"phase":{"ApplyExtrinsic":0},"event":{"index":"0x0000","data":null},"topics":[]}]'```

The last even here is an empty event but seems like there shouldn't be an empty event in this block.

**Comment by holygits** [comment] 2020-08-24 01:59
Could be related to `AssetInfoUpdated` event/tx

**Comment by AlexZhenWang** [comment] 2020-08-24 02:26
> Could be related to `AssetInfoUpdated` event/tx
Thanks for checking!

Yeah, exactly, the index of the third event is `0x0303`- `GenericAsset AssetInfoUpdated`.  Also, just share what I see, I see the Compact.decodeU8a() returns length 4 when decoding event
![image](https://user-images.githubusercontent.com/14008461/90996234-3ae35c00-e612-11ea-8e29-9e1870a11a8c.png), but the u8a are all used after decoding the first 3 events.

**Comment by wilfred-centrality** [comment] 2020-08-25 22:12
@holygits let's prioritise this between the transition UI launch and the transition processing event

**Comment by AlexZhenWang** [comment] 2020-08-25 22:20
Thank you 🙌 @wilfred-centrality !

**Comment by alexsednz** [comment] 2020-08-25 22:42
@KarishmaBothara This is likely to be caused by the fact that we haven't added our cennznet custom events (here AssetInfoUpdated) to metadata. But it's not just that. We have events in CENNZx for AddLiquidity for example that are not covered in the metadata. So when adding this, it would be good if you add all the others as well.

**Comment by AlexZhenWang** [comment] 2020-09-08 01:22
Thank you @alexsednz 👍

**Comment by holygits** [comment] 2020-10-22 03:26
support this will be in the next release, closed via #186

**Closed by holygits** 2020-10-22 03:26 UTC
Labels: bug
